import { Product } from "./types";

export const products: Product[] = [
  {
    id: "12cxsd",
    title: "Windows 11 Home Activation key",
    category: "operating-system",
    price: 19.99,
    icon: "windows/home.png",
    discount: 199.99,
    desc: `The Windows 11 operating system has been designed for both private individuals and more experienced customers. Multiple features have been updated and the interface has been revamped with a much tidier and user-friendly design. Specific enhancements focused on improving speed and security have been implemented. Another major functionality not to be overlooked is the ability to share and edit files from both desktop and tablet through cloud-sync capabilities, ensuring content is updated in real-time. the download will be very simple and you will receive everything you need for the installation by email within seconds of purchase. With the purchase and installation of Windows 11 Home, you will be able to install the latest and most updated Microsoft Office 2021 Suite.For the safety of your device we always recommend the installation of an Antivirus, you can choose your Antivirus by clicking here.`
  },
  {
    id: "32fawx",
    title: "Windows 11 Professional Activation key",
    category: "operating-system",
    price: 19.99,
    icon: "windows/pro.png",
    discount: 199.99,
  },
  {
    id: "47ftyx",
    title: "Windows 10 Home Activation key",
    category: "operating-system",
    price: 19.99,
    icon: "windows/home10.png",
    discount: 99.99,
  },
  {
    id: "92jaqx",
    title: "Windows 10 Professional Activation key",
    category: "operating-system",
    price: 19.99,
    icon: "windows/home10pro.png",
    discount: 99.99,
  },
  {
    id: "92yamp",
    title: "WINDOWS 10 PROFESSIONAL + OFFICE 2019 PROFESSIONAL PLUS – BUNDLE",
    category: "microsoft-office",
    price: 35.99,
    icon: "windows/office.png",
    discount: 355.99,
  },
  {
    id: "plae14",
    title: "WINDOWS 11 PROFESSIONAL + OFFICE 2021 PROFESSIONAL PLUS – BUNDLE",
    category: "microsoft-office",
    price: 35.99,
    icon: "windows/office21.png",
    discount: 355.99,
  },
  {
    id: "jano64",
    title: "Office 2016 Professional Plus Activation key – (PC)",
    category: "microsoft-office",
    price: 9.99,
    icon: "windows/officeplus.png",
    discount: 99.99,
  },
  {
    id: "ztal13",
    title:
      "Microsoft 365 Professional Plus Account 5 Devices – LifeTime subscription",
    category: "microsoft-office",
    price: 14.99,
    icon: "windows/office365.png",
    discount: 149.99,
  },
  {
    id: "hu12jl",
    title: "McAfee Total Protection – 5 Device 1 year",
    category: "antivirus-security",
    price: 29.99,
    icon: "windows/mcafee.png",
    discount: 299.99,
  },
  {
    id: "zp73ge",
    title: "Kaspersky Internet Security 2022",
    category: "antivirus-security",
    price: 29.99,
    icon: "windows/kaspersky.png",
    discount: 299.99,
  },
  {
    id: "xw85lp",
    title: "ESET NOD32 Antivirus 2022 – 2 Year License key",
    category: "antivirus-security",
    price: 29.99,
    icon: "windows/nod32.png",
    discount: 299.99,
  },
  {
    id: "la52mk",
    title: "Kaspersky Total Security 2022",
    category: "antivirus-security",
    price: 29.99,
    icon: "windows/kasperskytot.png",
    discount: 299.99,
  },
  {
    id: "la58qm",
    title: "Netflix Premium Subscription (1 Year)",
    category: "subscriptions",
    price: 29.99,
    icon: "windows/netflix1.png",
    discount: 255.99,
  },
  {
    id: "la12kz",
    title: "Netflix Premium Subscription (6 Months)",
    category: "subscriptions",
    price: 19.99,
    icon: "windows/netflix1.png",
    discount: 199.99,
  },
  {
    id: "la71gc",
    title: "Netflix Premium Subscription For 3 Month",
    category: "subscriptions",
    price: 9.99,
    icon: "windows/netflix1.png",
    discount: 25.99,
  },
  {
    id: "la46nb",
    title: "Spotify Premium Subscription (1 Year)",
    category: "subscriptions",
    price: 259.99,
    icon: "windows/spotify.png",
    discount: 29.99,
  },
  {
    id: "bz62jl",
    title: "Spotify Premium Subscription (6 Month)",
    category: "subscriptions",
    price: 19.99,
    icon: "windows/spotify.png",
    discount: 159.99,
  },
  {
    id: "ui32ml",
    title: "Streaming IP-TV (1 Year)",
    category: "subscriptions",
    price: 39.99,
    icon: "windows/iptv.png",
    discount: 599.99,
  },
  {
    id: "lp83ho",
    title: "Youtube Premium Subscription (1 Year)",
    category: "subscriptions",
    price: 39.99,
    icon: "windows/youtube.png",
    discount: 89.99,
  },
  {
    id: "mk56ab",
    title: "Youtube Premium Subscription (6 Month)",
    category: "subscriptions",
    price: 24.99,
    icon: "windows/youtube.png",
    discount: 59.99,
  },
];
